
export const EXERCISES = [
  // CHEST
  { name: "Barbell Bench Press",         muscleGroups: ["chest","triceps","shoulders"], equipment: "barbell",    movementType: "compound" },
  { name: "Incline Barbell Bench Press", muscleGroups: ["chest","triceps","shoulders"], equipment: "barbell",    movementType: "compound" },
  { name: "Decline Barbell Bench Press", muscleGroups: ["chest","triceps"],             equipment: "barbell",    movementType: "compound" },
  { name: "Dumbbell Bench Press",        muscleGroups: ["chest","triceps","shoulders"], equipment: "dumbbell",   movementType: "compound" },
  { name: "Incline Dumbbell Press",      muscleGroups: ["chest","shoulders"],           equipment: "dumbbell",   movementType: "compound" },
  { name: "Dumbbell Fly",                muscleGroups: ["chest"],                       equipment: "dumbbell",   movementType: "isolation" },
  { name: "Incline Dumbbell Fly",        muscleGroups: ["chest"],                       equipment: "dumbbell",   movementType: "isolation" },
  { name: "Cable Fly",                   muscleGroups: ["chest"],                       equipment: "cable",      movementType: "isolation" },
  { name: "Low Cable Fly",               muscleGroups: ["chest"],                       equipment: "cable",      movementType: "isolation" },
  { name: "High Cable Fly",              muscleGroups: ["chest"],                       equipment: "cable",      movementType: "isolation" },
  { name: "Push-Up",                     muscleGroups: ["chest","triceps","shoulders"], equipment: "bodyweight", movementType: "compound" },
  { name: "Wide Push-Up",                muscleGroups: ["chest"],                       equipment: "bodyweight", movementType: "compound" },
  { name: "Dips (Chest)",                muscleGroups: ["chest","triceps"],             equipment: "bodyweight", movementType: "compound" },
  { name: "Pec Deck Machine",            muscleGroups: ["chest"],                       equipment: "machine",    movementType: "isolation" },
  { name: "Smith Machine Bench Press",   muscleGroups: ["chest","triceps"],             equipment: "machine",    movementType: "compound" },
  { name: "Chest Press Machine",         muscleGroups: ["chest","triceps"],             equipment: "machine",    movementType: "compound" },
  { name: "Landmine Press",              muscleGroups: ["chest","shoulders"],           equipment: "barbell",    movementType: "compound" },

  // BACK
  { name: "Deadlift",                    muscleGroups: ["back","glutes","hamstrings"],  equipment: "barbell",    movementType: "compound" },
  { name: "Romanian Deadlift",           muscleGroups: ["hamstrings","glutes","back"],  equipment: "barbell",    movementType: "compound" },
  { name: "Barbell Row",                 muscleGroups: ["back","biceps"],               equipment: "barbell",    movementType: "compound" },
  { name: "Pendlay Row",                 muscleGroups: ["back","biceps"],               equipment: "barbell",    movementType: "compound" },
  { name: "T-Bar Row",                   muscleGroups: ["back","biceps"],               equipment: "machine",    movementType: "compound" },
  { name: "Dumbbell Row",                muscleGroups: ["back","biceps"],               equipment: "dumbbell",   movementType: "compound" },
  { name: "Cable Row",                   muscleGroups: ["back","biceps"],               equipment: "cable",      movementType: "compound" },
  { name: "Lat Pulldown",                muscleGroups: ["back","biceps"],               equipment: "cable",      movementType: "compound" },
  { name: "Wide Grip Lat Pulldown",      muscleGroups: ["back"],                        equipment: "cable",      movementType: "compound" },
  { name: "Close Grip Lat Pulldown",     muscleGroups: ["back","biceps"],               equipment: "cable",      movementType: "compound" },
  { name: "Pull-Up",                     muscleGroups: ["back","biceps"],               equipment: "bodyweight", movementType: "compound" },
  { name: "Chin-Up",                     muscleGroups: ["back","biceps"],               equipment: "bodyweight", movementType: "compound" },
  { name: "Neutral Grip Pull-Up",        muscleGroups: ["back","biceps"],               equipment: "bodyweight", movementType: "compound" },
  { name: "Straight Arm Pulldown",       muscleGroups: ["back"],                        equipment: "cable",      movementType: "isolation" },
  { name: "Face Pull",                   muscleGroups: ["shoulders","back"],            equipment: "cable",      movementType: "isolation" },
  { name: "Seated Cable Row",            muscleGroups: ["back","biceps"],               equipment: "cable",      movementType: "compound" },
  { name: "Rack Pull",                   muscleGroups: ["back","glutes"],               equipment: "barbell",    movementType: "compound" },
  { name: "Good Morning",               muscleGroups: ["back","hamstrings"],            equipment: "barbell",    movementType: "compound" },

  // SHOULDERS
  { name: "Overhead Press",             muscleGroups: ["shoulders","triceps"],          equipment: "barbell",    movementType: "compound" },
  { name: "Seated Dumbbell Press",      muscleGroups: ["shoulders","triceps"],          equipment: "dumbbell",   movementType: "compound" },
  { name: "Arnold Press",               muscleGroups: ["shoulders"],                    equipment: "dumbbell",   movementType: "compound" },
  { name: "Lateral Raise",             muscleGroups: ["shoulders"],                     equipment: "dumbbell",   movementType: "isolation" },
  { name: "Cable Lateral Raise",       muscleGroups: ["shoulders"],                     equipment: "cable",      movementType: "isolation" },
  { name: "Front Raise",               muscleGroups: ["shoulders"],                     equipment: "dumbbell",   movementType: "isolation" },
  { name: "Rear Delt Fly",             muscleGroups: ["shoulders","back"],              equipment: "dumbbell",   movementType: "isolation" },
  { name: "Reverse Pec Deck",          muscleGroups: ["shoulders","back"],              equipment: "machine",    movementType: "isolation" },
  { name: "Upright Row",               muscleGroups: ["shoulders","traps"],             equipment: "barbell",    movementType: "compound" },
  { name: "Machine Shoulder Press",    muscleGroups: ["shoulders","triceps"],           equipment: "machine",    movementType: "compound" },
  { name: "Push Press",                muscleGroups: ["shoulders","triceps"],           equipment: "barbell",    movementType: "compound" },
  { name: "Shrugs",                    muscleGroups: ["traps"],                         equipment: "barbell",    movementType: "isolation" },
  { name: "Dumbbell Shrugs",           muscleGroups: ["traps"],                         equipment: "dumbbell",   movementType: "isolation" },

  // BICEPS
  { name: "Barbell Curl",              muscleGroups: ["biceps"],                        equipment: "barbell",    movementType: "isolation" },
  { name: "EZ Bar Curl",               muscleGroups: ["biceps"],                        equipment: "barbell",    movementType: "isolation" },
  { name: "Dumbbell Curl",             muscleGroups: ["biceps"],                        equipment: "dumbbell",   movementType: "isolation" },
  { name: "Hammer Curl",               muscleGroups: ["biceps","forearms"],             equipment: "dumbbell",   movementType: "isolation" },
  { name: "Incline Dumbbell Curl",     muscleGroups: ["biceps"],                        equipment: "dumbbell",   movementType: "isolation" },
  { name: "Concentration Curl",        muscleGroups: ["biceps"],                        equipment: "dumbbell",   movementType: "isolation" },
  { name: "Preacher Curl",             muscleGroups: ["biceps"],                        equipment: "barbell",    movementType: "isolation" },
  { name: "Cable Curl",                muscleGroups: ["biceps"],                        equipment: "cable",      movementType: "isolation" },
  { name: "Machine Curl",              muscleGroups: ["biceps"],                        equipment: "machine",    movementType: "isolation" },
  { name: "Spider Curl",               muscleGroups: ["biceps"],                        equipment: "dumbbell",   movementType: "isolation" },

  // TRICEPS
  { name: "Close Grip Bench Press",    muscleGroups: ["triceps","chest"],               equipment: "barbell",    movementType: "compound" },
  { name: "Skull Crushers",            muscleGroups: ["triceps"],                       equipment: "barbell",    movementType: "isolation" },
  { name: "Tricep Pushdown",           muscleGroups: ["triceps"],                       equipment: "cable",      movementType: "isolation" },
  { name: "Overhead Tricep Extension", muscleGroups: ["triceps"],                       equipment: "dumbbell",   movementType: "isolation" },
  { name: "Dips (Triceps)",            muscleGroups: ["triceps","chest"],               equipment: "bodyweight", movementType: "compound" },
  { name: "Diamond Push-Up",           muscleGroups: ["triceps","chest"],               equipment: "bodyweight", movementType: "compound" },
  { name: "Rope Pushdown",             muscleGroups: ["triceps"],                       equipment: "cable",      movementType: "isolation" },
  { name: "Single Arm Pushdown",       muscleGroups: ["triceps"],                       equipment: "cable",      movementType: "isolation" },
  { name: "Tricep Kickback",           muscleGroups: ["triceps"],                       equipment: "dumbbell",   movementType: "isolation" },
  { name: "Machine Tricep Extension",  muscleGroups: ["triceps"],                       equipment: "machine",    movementType: "isolation" },

  // LEGS
  { name: "Barbell Back Squat",        muscleGroups: ["quads","glutes","hamstrings"],   equipment: "barbell",    movementType: "compound" },
  { name: "Front Squat",               muscleGroups: ["quads","glutes"],                equipment: "barbell",    movementType: "compound" },
  { name: "Goblet Squat",              muscleGroups: ["quads","glutes"],                equipment: "dumbbell",   movementType: "compound" },
  { name: "Bulgarian Split Squat",     muscleGroups: ["quads","glutes"],                equipment: "dumbbell",   movementType: "compound" },
  { name: "Leg Press",                 muscleGroups: ["quads","glutes","hamstrings"],   equipment: "machine",    movementType: "compound" },
  { name: "Hack Squat",                muscleGroups: ["quads"],                         equipment: "machine",    movementType: "compound" },
  { name: "Leg Extension",             muscleGroups: ["quads"],                         equipment: "machine",    movementType: "isolation" },
  { name: "Leg Curl",                  muscleGroups: ["hamstrings"],                    equipment: "machine",    movementType: "isolation" },
  { name: "Seated Leg Curl",           muscleGroups: ["hamstrings"],                    equipment: "machine",    movementType: "isolation" },
  { name: "Stiff Leg Deadlift",        muscleGroups: ["hamstrings","glutes"],           equipment: "barbell",    movementType: "compound" },
  { name: "Hip Thrust",                muscleGroups: ["glutes"],                        equipment: "barbell",    movementType: "isolation" },
  { name: "Dumbbell Hip Thrust",       muscleGroups: ["glutes"],                        equipment: "dumbbell",   movementType: "isolation" },
  { name: "Walking Lunge",             muscleGroups: ["quads","glutes"],                equipment: "dumbbell",   movementType: "compound" },
  { name: "Reverse Lunge",             muscleGroups: ["quads","glutes"],                equipment: "dumbbell",   movementType: "compound" },
  { name: "Step Up",                   muscleGroups: ["quads","glutes"],                equipment: "dumbbell",   movementType: "compound" },
  { name: "Standing Calf Raise",       muscleGroups: ["calves"],                        equipment: "machine",    movementType: "isolation" },
  { name: "Seated Calf Raise",         muscleGroups: ["calves"],                        equipment: "machine",    movementType: "isolation" },
  { name: "Smith Machine Squat",       muscleGroups: ["quads","glutes"],                equipment: "machine",    movementType: "compound" },
  { name: "Sumo Deadlift",             muscleGroups: ["glutes","hamstrings","back"],    equipment: "barbell",    movementType: "compound" },
  { name: "Glute Kickback",            muscleGroups: ["glutes"],                        equipment: "cable",      movementType: "isolation" },

  // CORE
  { name: "Plank",                     muscleGroups: ["core"],                          equipment: "bodyweight", movementType: "isolation" },
  { name: "Side Plank",                muscleGroups: ["core"],                          equipment: "bodyweight", movementType: "isolation" },
  { name: "Crunch",                    muscleGroups: ["core"],                          equipment: "bodyweight", movementType: "isolation" },
  { name: "Sit-Up",                    muscleGroups: ["core"],                          equipment: "bodyweight", movementType: "isolation" },
  { name: "Leg Raise",                 muscleGroups: ["core"],                          equipment: "bodyweight", movementType: "isolation" },
  { name: "Hanging Leg Raise",         muscleGroups: ["core"],                          equipment: "bodyweight", movementType: "isolation" },
  { name: "Russian Twist",             muscleGroups: ["core"],                          equipment: "bodyweight", movementType: "isolation" },
  { name: "Cable Crunch",              muscleGroups: ["core"],                          equipment: "cable",      movementType: "isolation" },
  { name: "Ab Rollout",                muscleGroups: ["core"],                          equipment: "bodyweight", movementType: "isolation" },
  { name: "Dead Bug",                  muscleGroups: ["core"],                          equipment: "bodyweight", movementType: "isolation" },
  { name: "Bicycle Crunch",            muscleGroups: ["core"],                          equipment: "bodyweight", movementType: "isolation" },
  { name: "Mountain Climber",          muscleGroups: ["core","cardio"],                 equipment: "bodyweight", movementType: "compound" },
];

export const MUSCLE_GROUPS = ["chest","back","shoulders","biceps","triceps","quads","hamstrings","glutes","calves","core","traps","forearms","cardio"];
export const EQUIPMENT_TYPES = ["barbell","dumbbell","cable","machine","bodyweight"];
